### ISSUE TITLE
ClusterRoleBinding missing namespace in csi-provisioner-rbac.yaml

### ISSUE THREAD

**Issue by fbarreir** [cernops/cvmfs-csi#17]
Executing this yaml ClusterRoleBinding fails because it's missing a required namespace:
https://github.com/cernops/cvmfs-csi/blob/master/deployments/kubernetes/csi-provisioner-rbac.yaml#L58

```
...
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvmfs-csi-provisioner-role
subjects:
  - kind: ServiceAccount
    name: cvmfs-csi-provisioner
    namespace: cvmfs
...
```

I guess this one doesn't matter when you'll have the helm chart for installation.
