### ISSUE TITLE
Comment out repositories value as it is being merged with custom values

### ISSUE THREAD

**Issue by isantospardo** [cernops/cvmfs-csi#23]
When cvmfs-csi helm chart is being handled by argo-cd, the values specified in `repositories` are being merged to the custom values I am passing, so this means:
```
helm:
      values: |
        repositories:
          mykey: myvalue
```
Is merging https://github.com/cernops/cvmfs-csi/blob/master/deployments/helm/cvmfs-csi/values.yaml#L41
With the result of:
```
mykey: myvalue
cern-repo: repository.cern.ch
```
I assume `cern-repo` was added as an example, I would suggest to delete this parameter

As a workaround in argo-cd, I added the following to get rid of `cern-repo`
```
helm:
      values: |
        repositories:
          mykey: myvalue
          cern-repo: null
```
